### ISSUE TITLE
option to copy btc address 

### ISSUE THREAD

**Issue by papermate** [btcontract/wallet#10]
Hello,
I'm using the app and I really like it.
If I have to receive btc, though, and send the link to just my address someone via email, text or such I would like to just click on my address and copy it.

Right now the workaround is menu > ask for payment > set an amount >  copy > paste > strip the resulting request from the beginning "bitcoin" and ending "amount"

Not really smooth and it feels to me like a very basic feature.

All the best

**Comment by btcontract** [comment]
Hi,
the address copy button is there already and has been for quite a long time, I've attached a picture of now it looks on my phone (notice the button on the bottom). Is it different on your device?  

![photo_2016-07-20_09-14-07](https://cloud.githubusercontent.com/assets/9870980/16976926/75cecffa-4e5b-11e6-8132-bafb89d31d60.jpg)

**Comment by papermate** [comment]
Hello,
yes, it is actually different on my device, the bottom gets cut out!
May I suggest to put both the [share image] and [copy address] buttons on the top, to avoid this happening in smaller screen devices?

My specs:
Samsung Galaxy W (GT-I8150)
screen is 3.7", 480x800 pixels 
OS: Cyanogenmod 10.2 (based on androd 4.3.1)

I attach screenshot
![sgw](https://cloud.githubusercontent.com/assets/12624801/17001602/375d161c-4eb7-11e6-9058-7e8484abb892.png)

**Comment by btcontract** [comment]
>> May I suggest to put both the [share image] and [copy address] buttons on the top, to avoid this happening in smaller screen devices?  

Yes, this is a good idea. I'll do it in the next update (which I plan to roll out today btw). Thanks for bringing this up!

**Comment by btcontract** [comment]
>> May I suggest to put both the [share image] and [copy address] buttons on the top, to avoid this happening in smaller screen devices?  

Yes, this is a good idea. I'll do it in the next update (which I plan to roll out today btw). Thanks for bringing this up!

**Comment by papermate** [comment]
Awesome, can't wait for the upgrade to be available on f-droid.
Sincere thanks for your wallet!

**Comment by tracihaire** [comment]
I am very new with this bit thing I can us all the help anyone wants to give

**Comment by btcontract** [comment]
@tracihaire you might want to continue our conversation via email, mine is anton.kumaigorodskiy@outlook.com
Please describe your issues in detail there.
