### ISSUE TITLE
can't bind Keystone hardware wallet

### ISSUE THREAD

**Issue by caixiao-QA** [btcontract/wallet#111]
SBW app version: V2.4.18-86
Keystone hardware Wallet version:B-2.5, Watch-only Wallet:Generic Wallet

Add hardware wallet and scan Keystone hardware wallet,but cant bind.The screen recording is as follows.
https://user-images.githubusercontent.com/37337093/142371365-a02ad7c1-6851-4793-b1f3-e64d6d25cfce.mp4

Keystone SYNC QRcode（Native Segwit):
![image](https://user-images.githubusercontent.com/37337093/142370861-bb5b9d77-22ba-4527-9c8f-414b44a2e595.png)

**Comment by btcontract** [comment]
Can you please provide the following for this QR code:
- master key fingerprint (as `Long` or hex).
- BIP84 account key as hex.

This will simplify debugging as I don't have this HW on hand.

**Comment by btcontract** [comment]
Alternatively, a first Bitcoin address generated by BIP84 account.

**Comment by btcontract** [comment]
Also feel free to test with `wget https://sbw.app/SBW-2.4.19.apk`

**Comment by caixiao-QA** [comment]
> Can you please provide the following for this QR code:
> 
> * master key fingerprint (as `Long` or hex).
> * BIP84 account key as hex.
> 
> This will simplify debugging as I don't have this HW on hand.

Master fingerprint：5271c01
Derivation：m/84'/0'/0'
zpub：zpub6rcabYFcdr41zyUNRWRyHYs2Sm86E5XV8RjjRzTFYsiCngteeZnkwaF2xuhjmM6kpHjuNpFW42BMhzPmFwXt48e1FhddMB7xidZzN4SF24K

**Comment by caixiao-QA** [comment]
> Alternatively, a first Bitcoin address generated by BIP84 account.
path：m/84'/0'/0'/0/0
address：bc1q9unqc738dxjg5mk8zqtz33zg59cahrj29s24lp

![image](https://user-images.githubusercontent.com/37337093/142796379-2fbf0d70-2839-4b16-b4ee-77a0dd7830b3.png)

**Comment by soralit** [comment]
Hey @btcontract , I'm a developer from Keystone. I'm really excited to see such a smart, graceful(I really like Scala and FP) wallet supporting us! Just @me if you have any problem in the integration work. 😄

**Comment by BitcoinLixin** [comment]
Hey @btcontract would you kindly use Simple Bitcoin Wallet's official twitter account to DM me so that I can send you a free sample device?

My twitter - https://twitter.com/BitcoinLixin

**Comment by btcontract** [comment]
@BitcoinLixin thanks a lot, will do.

@caixiao-QA I've fixed it as far as I can tell. Once added all important data matches provided when scanning a reference QR code here. This can be tested in release `2.4.19`: https://github.com/btcontract/wallet/releases/tag/2.4.19

**Comment by soralit** [comment]
Hey @btcontract , we just tested the release and found it a little difficult to read the psbt qr. 

I have read the QR part of the code base, and have some recommendations: 
> 1. it seems the arguments are passed in wrong order, the constructor of UREncoder is defined as `public UREncoder(UR ur, int maxFragmentLen, int minFragmentLen, long firstSeqNum)` https://github.com/btcontract/wallet/blob/master/app/src/main/java/com/btcontract/wallet/BaseActivity.scala#L539
> 2. it would be good if the PSBT can be constructed as [`crypto-psbt`](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-006-urtypes.md#partially-signed-bitcoin-transaction-psbt-crypto-psbt), Keystone supports read PSBT from `bytes` but it is just for compatibility. 
> 3. it would be good if the QR string can be uppercased which can reduce the QR data size, per https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md#introduction

**Comment by btcontract** [comment]
@soralit thanks, indeed max/min values were displaced, I've fixed that and applied other suggestions in https://github.com/btcontract/wallet/commit/36e5dec30a0295f7090e310daa1a51996c322075.

**Comment by btcontract** [comment]
I've tested and made sure everything works in https://github.com/btcontract/wallet/releases/tag/2.4.22. Guess feel free to close this if no issues are found on your side.
