### ISSUE TITLE
Weirdness when resyncing block chain with unconfirmed transactions

### ISSUE THREAD

**Issue by hughdavenport** [btcontract/wallet#12]
Just started using this from fdroid (version 1.072).

Had around 0.1btc which I transfered a few days ago in, then today I sent out some transactions and while they were still unconfirmed I refreshed block chain then they displayed as incoming with the change amount. Or it groups them together. Finally displayed right after everything confirmed. Weirdly the balance in the top displayed correct all the time. I've attached some screenshots showing what I saw.

![tmp_25574-screenshot_20160910-073355387419955](https://cloud.githubusercontent.com/assets/1222607/18400787/85c60916-772b-11e6-84e6-1c72a76ff510.png)
![tmp_25574-screenshot_20160910-0736522125723133](https://cloud.githubusercontent.com/assets/1222607/18400796/8b872088-772b-11e6-97e1-e0cf67face7c.png)
![tmp_25574-screenshot_20160910-074357-1387389491](https://cloud.githubusercontent.com/assets/1222607/18400798/8f13f212-772b-11e6-95d7-f4ad38298174.png)

**Comment by hughdavenport** [comment]
Third image is correct. First one shows incoming change? Second one has a missing transaction from the other day and has yet a different incoming value.

**Comment by btcontract** [comment]
Well, this is a complicated issue. Technically, I think, what's happening is wallet receives a spent unconfirmed transaction from connected node's mempool before it receives a "spent-from" transaction  which causes such a behavior. 

Unfortunately, I don't think I'm qualified enough to edit bitcoinj's internals which govern the related logic. In general, unconfirmed transactions currently don't do well with lite wallets (https://btcontract.com/#unconfirmed-transactions), lots of weird stuff can happen before transaction is finally confirmed.

**Comment by hughdavenport** [comment]
Yeh. Was  just a bit confusing. If it is an issue with underlying library then potentially can close this as it is correct now. Thoughts?
