### ISSUE TITLE
Link Ledger Nano View-Only Hardware Wallet

### ISSUE THREAD

**Issue by MountainMaster** [btcontract/wallet#120]
Hello,

I am having problems finding / creating a QR Code that works with the xPub Key I got from Ledger Live. My tries ended in a "error_nothing_useful" error.

What format needs a QR to have for the SBW to recognize it when adding a Hardware Wallet?

Best
Tobias

Information how the view the xPub Key for Ledger Nano S Accounts:
https://support.ledger.com/hc/en-us/articles/360011069619-Extended-public-key?docs=true

**Comment by btcontract** [comment]
I assume the issue could be that SBW only supports `zpub` currently which is an extended public key for BIP84 account type (native segwit). If the pubkey data starts with `xpub` and not `zpub` then this indicates it's not a BIP84 account key.

**Comment by MountainMaster** [comment]
Ah thank you very much for the fast reply. Yes that's most likely the case.

The Account I try to add is BIP84 native segwit but i cant get another key that xpub. I try my luck than with ledger support and report back if I am successful.

**Comment by MountainMaster** [comment]
Managed to use this tool and transforme the xpub to zpub :)
https://github.com/jlopp/xpub-converter

**Comment by btcontract** [comment]
Great, the reason SBW does not do that automatically is provided `xpub` very well may not actually encode a BIP84 account, so assuming that and moving forward would be quite a leap of faith which may lead to surprises in future.
