### ISSUE TITLE
LNURL on lightning.gifts doesn't work with Tor

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#121]
Steps to reproduce:

- go to https://lightning.gifts/
- choose LNURL at the right
- make sure SBW uses the built-in Tor
- scan the QR
- 
![Screenshot_20211213-124319](https://user-images.githubusercontent.com/184066/145788977-4c25737e-5b68-45ec-933c-8ca468641da7.png)

It works if Tor isn't enabled in the app. Might have something to do with the JSON length, it's [huge](https://api.lightning.gifts/lnurl).

**Comment by btcontract** [comment]
This is an issue on https://lightning.gifts/ end, they respond with different and wrong content if request comes via Tor.

**Comment by rkfg** [comment]
Didn't check it manually, my bad! Thanks. Really weird they do that but little we can do...
