### ISSUE TITLE
Can't reconnect after inactivity when Tor is enabled

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#122]
Steps to reproduce:
- enable Tor in the app
- see if everything works and the channels are active
- minimize the app and put the phone aside for a while (5-10 minutes)
- switch back to the app and login
- it stays offline indefinitely, channels are inactive, nothing (i.e. everything that needs connectivity) works

It's possible to swipe it off (terminate the process) and restart, then it connects normally. This also doesn't happen if Tor is turned off.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/c1d23dacd3f2c8a556ad12cb4355c443967683fd.
