### ISSUE TITLE
Unable to send lightning payment

### ISSUE THREAD

**Issue by secondl1ght** [btcontract/wallet#125]
Same as #124 but that issue was closed. I was aware of the fee and tried sending a lower amount, I tried sending 50 sats which should have enough room for the fee but the 'Ok' button is still disabled.

**Comment by btcontract** [comment]
Can you share or create an invoice which is causing this?

**Comment by secondl1ght** [comment]
I figured out what the issue is after further testing: 

If you scan an invoice for an amount over your spendable amount and then lower the sat amount to an amount that will work, the 'Ok' button still will be disabled even though you are now sending an acceptable amount. It is still using the disable button because the original invoice is over your limit.

If that makes sense?

**Comment by btcontract** [comment]
> It is still using the disable button because the original invoice is over your limit.

Yes, it does. This is an expected behavior since a payment of amount which is lower than requested would be rejected by receiver anyway (according to LN protocol convention). 

What will work here is SPLIT button which allows two or more wallets to pay to the same invoice in parts.

**Comment by secondl1ght** [comment]
Ok sounds good, I didn't know this was expected behavior. Thanks for letting me know, will close now.
