### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [btcontract/wallet#126]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 112  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on wallet (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve wallet's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by btcontract** [comment]
Yes, please do share these gists, thanks.

**Comment by misterAnderson90** [comment]
Hello @btcontract,

From the 112 warnings that CogniCrypt reported, we randomly selected 5 gists to share with you. If you are interested, we can share the report with all warnings. 

[Gist 01 - Cipher](https://gist.github.com/misterAnderson90/bc47b018b902cdc0ead8b0f8e2e512f6)
[Gist 02 - Mac](https://gist.github.com/misterAnderson90/8fe61561dba35bb793c2a4c1cd3de87a)
[Gist 03 - SecretKeySpec](https://gist.github.com/misterAnderson90/ea30f85f98c74ee38c0701afb63acb09)
[Gist 04 - MessageDigest](https://gist.github.com/misterAnderson90/009a6e93c7a88e3409b72d2960fe5eed)
[Gist 05 - IvParameterSpec](https://gist.github.com/misterAnderson90/ef29db2979fb70f762cf35ffc0112830)

For any doubts, you can comment directly in the gists and we can clarify the issues.  

Best regards,

**Comment by btcontract** [comment]
Thanks, looking at there I don't see issues yet:

**Comment by btcontract** [comment]
Thanks, looking at these I don't see issues yet:


[Gist 01 - Cipher](https://gist.github.com/misterAnderson90/bc47b018b902cdc0ead8b0f8e2e512f6) - `init` method is called in `cipher` method prior to calling `doFinal`, perhaps analyzer was not able to see this.

[Gist 02 - Mac](https://gist.github.com/misterAnderson90/8fe61561dba35bb793c2a4c1cd3de87a) - `bitcoinj` has been removed from project recently.

[Gist 03 - SecretKeySpec](https://gist.github.com/misterAnderson90/ea30f85f98c74ee38c0701afb63acb09) - `bitcoinj` has been removed from project recently.

[Gist 04 - MessageDigest](https://gist.github.com/misterAnderson90/009a6e93c7a88e3409b72d2960fe5eed) - `bitcoinj` has been removed from project recently.

[Gist 05 - IvParameterSpec](https://gist.github.com/misterAnderson90/ef29db2979fb70f762cf35ffc0112830) - `initVector` data is supposed to be randomized prior to being supplied to method `cipher`.
