### ISSUE TITLE
Unable to login with lnurl-auth when tor is enabled

### ISSUE THREAD

**Issue by tweili** [btcontract/wallet#128]
lnurl-auth (for example https://lightninglogin.live/) is not working with tor enabled:
![screenshot-lnurl-auth](https://user-images.githubusercontent.com/18072425/146807466-d4cde298-9017-4b7c-93a7-03fe5eee76f8.png)

**Comment by btcontract** [comment]
This looks like connection timeout meaning tor was not able to establish a connection within 15 seconds.

Can you try this out again after OFFLINE badge disappears in a wallet (which means tor is definitely connected).

**Comment by tweili** [comment]
Thanks for your answer, it works now.
