### ISSUE TITLE
SBW cannot parse Lightning addresses if they have non-latin characters

### ISSUE THREAD

**Issue by Liongrass** [btcontract/wallet#129]
REPRO:

Enter a Lightning address ([as specified here](https://lightningaddress.com/)) which contains special characters, for example `leo@比特幣.組織.香港` into the field "Bitocin address, invoice, email..." and press OK.

EXPECTED:

Move on to the "Lightning payment link" dialogue, as is the case for other latin-only Lightning addresses (e.g. leo@bitcoin.org.hk)

ACTUAL:

The field is cleared.

**Comment by btcontract** [comment]
This behavior is compliant with spec here: https://github.com/fiatjaf/lnurl-rfc/blob/luds/16.md.

Specifically: `The <username> is limited to a-z0-9-_.. `

**Comment by Liongrass** [comment]
Hi! The <username> part of the Lightning Address above is limited to `a-z0-9-_..`, e.g. `leo`. The spec does not limit the domain part of the Lightning Address, e.g. `比特幣.組織.香港`.

Any valid domain should also be able to host valid Lightning Addresses. I hope this can be reopened and make it into a future update!

**Comment by fiatjaf** [comment]
Non-ascii domains are not allowed in many places, I think it's because they're used in scams by faking ascii letters. Instead punycode is used.

My suggestion is that you try typing the lightning address as punycode in SBW: https://www.punycoder.com
