### ISSUE TITLE
Feature: add different exchange rates

### ISSUE THREAD

**Issue by hughdavenport** [btcontract/wallet#13]
I see when you click on details it gives an approximate dollar value which I assume is USD. It would be cool if you could change that somewhere.

Also being able to see dollar value on transaction list would be good for a glance to see how much you have. And how much you've spent recently.

**Comment by btcontract** [comment]
> I see when you click on details it gives an approximate dollar value which I assume is USD. It would be cool if you could change that somewhere.  

I't already possible, although a bit unintuitive: on "send" and "request payment" popups one can switch between USD, EUR and CNY and the choice affects the whole application. I should probably transfer that to a settings popup.

> Also being able to see dollar value on transaction list would be good for a glance to see how much you have.

Yes, this one is in the works.

**Comment by hughdavenport** [comment]
Any works on extending that for more currencies? Happy to help if you point me in the right direction

**Comment by btcontract** [comment]
It's a bit tricky. The goal here is to be fail-safe so wallet pulls rates randomly from three different sources (https://github.com/btcontract/wallet/blob/master/app/src/main/java/com/btcontract/wallet/helper/PeriodicHttp.scala#L69-L73, maybe more in future), their pair sets are not identical and they even add/remove them from time to time. 

So I just picked three most popular and less likely to be removed. This can be extended of course with some work-arounds for removed pairs but it's not my priority atm.
