### ISSUE TITLE
Biometrics not working properly

### ISSUE THREAD

**Issue by tulio150** [btcontract/wallet#132]
After activating biometrics, I get mutiple fingerprint requests, and sometimes after about 3 or 5 inputs, the app just closes.

Samsung Galaxy Note 9

**Comment by btcontract** [comment]
Is there any kind of error message on failed attempts? Could this be just something like scanner not working properly and then phone reacting to too much unsuccessful attempts?

**Comment by tulio150** [comment]
No error, just keeps asking for the fingerprint ant then just works or fail silently. Can't know for sure if it's in the phone or the app. Other apps are working fine. Phone has original firmware without root.

**Comment by prayank23** [comment]
Biometrics should be removed any from a bitcoin wallet

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/ce7ab77e9f34fada3e4769e4146445fa4b987644. 

There's now an option to use a built in PIN in case if fingerprint does not work right for whatever reason or user wants to avoid it.
