### ISSUE TITLE
UI issues when device language is RTL

### ISSUE THREAD

**Issue by EZ0010** [btcontract/wallet#134]
I love this wallet but when I set the device language to Arabic (a RTL language) some elements on the UI overlap each other.

I think the best fix for this (if possible) is to not let the app mirror its UI when system is RTL until there is a support for other languages other than english.
Screenshot:
![photo_2021-12-29 14 14 44](https://user-images.githubusercontent.com/75021359/147656711-7e43ff6f-13fc-4e21-999c-531fe707745c.jpeg)

**Comment by btcontract** [comment]
Thanks for reporting this, I've restricted RTL in https://github.com/btcontract/wallet/commit/82897dcee9140e3ec5406f04dd77e48dc74f881c, will get to properly fixing this at a later time.
