### ISSUE TITLE
failed negotiation of the reserve and dust limits when trying to open channel with c-lightning node

### ISSUE THREAD

**Issue by raphjaph** [btcontract/wallet#135]
I tried to open a channel between SBW and a c-lightning node and got the following error:

![error](https://user-images.githubusercontent.com/25913312/147751764-be8fcda1-d5c3-4846-92a6-a84db205ba46.png)

It seems as though there is a failed negotiation of the reserve and dust limits.
The default `dust_limit_satoshis` is 546 but eclair/immortan seems to be 354. Commit `7d9aab282fd879332b14110f8ae7ba6e3700ca0e` is where the immortan library makes the change from 546 to 354. 

Do I have to change something in the c-lightning config to allow this lower dust limit?

**Comment by btcontract** [comment]
I think this was a joint effort by all implementations since it was recognized that segwit allows for lower limits. Perhaps an old c-lightning node?

**Comment by raphjaph** [comment]
I will compile the lightning node from the master branch and then try again. But just looking at `lightning/bitcoin/chainparams.c` in the repo it still shows a `dust_limit` of 546. I could change this to 354 but I'm scared I'll shoot myself in the foot somehow. Anyways, it looks like it's probably a config problem on c-lightning's side.

```
const struct chainparams networks[] = {
    {.network_name = "bitcoin",
     .onchain_hrp = "bc",
     .lightning_hrp = "bc",
     .bip70_name = "main",
     .genesis_blockhash = {{{.u.u8 = {0x6f, 0xe2, 0x8c, 0x0a, 0xb6, 0xf1, 0xb3,
				      0x72, 0xc1, 0xa6, 0xa2, 0x46, 0xae, 0x63,
				      0xf7, 0x4f, 0x93, 0x1e, 0x83, 0x65, 0xe1,
				      0x5a, 0x08, 0x9c, 0x68, 0xd6, 0x19, 0x00,
				      0x00, 0x00, 0x00, 0x00}}}},
     .rpc_port = 8332,
     .cli = "bitcoin-cli",
     .cli_args = NULL,
     .cli_min_supported_version = 150000,
     .dust_limit = { 546 },
     /* BOLT #2:
      *
      * The sending node:
      *...
      *   - MUST set `funding_satoshis` to less than 2^24 satoshi.
      */
     .max_funding = AMOUNT_SAT_INIT((1 << 24) - 1),
     .max_payment = AMOUNT_MSAT_INIT(0xFFFFFFFFULL),
     /* "Lightning Charge Powers Developers & Blockstream Store" */
     .when_lightning_became_cool = 504500,
     .p2pkh_version = 0,
     .p2sh_version = 5,
     .testnet = false,
     .fee_asset_tag = NULL,
     .bip32_key_version = {.bip32_pubkey_version = BIP32_VER_MAIN_PUBLIC,
			   .bip32_privkey_version = BIP32_VER_MAIN_PRIVATE},
     .is_elements = false},
.
.
.
```

**Comment by raphjaph** [comment]
For anyone stumbling upon this. I had to change the `.dust_limit` in `lightning/bitcoin/chainparams.c` from 546 to 354 in and then recompile. C-Lightning doesn't use the lowered dust limit by default.
