### ISSUE TITLE
Incorrect exchange rate for sats in usd

### ISSUE THREAD

**Issue by prayank23** [btcontract/wallet#137]
Steps to reproduce:

1. Open app
2. Tap 'receive'
3. Select bitcoin address or ln invoice
4. Enter below amounts and see the price in USD
    ```
    0.0000001 BTC
    0.00000001 BTC
    ```

Incorrect exchange rate:

![image](https://user-images.githubusercontent.com/13405205/149407037-47b3b13a-7072-47fe-a336-94d2849fc996.png)

![image](https://user-images.githubusercontent.com/13405205/149407049-34b04416-6ea7-4a47-9f52-9a65d4f316cd.png)

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/f96632adf2ad7b30260b2ea25f3f2a4ae598f9e4.
