### ISSUE TITLE
SBW does not recognize LN QR codes

### ISSUE THREAD

**Issue by notnout** [btcontract/wallet#140]
I keep having issues with SBW (on Android) not being able to recognize LN QR codes. 
E.g. https://www.plebpay.com/5a2935d1-9cf3-4710-8405-99cb42d48154 works well in Muun and Breez, but SBW does not recognize it. 
I open the camera in the app with the "[  ]" button, point it at the QR, but then nothing happens.

**Comment by btcontract** [comment]
QR code on that page is missing a so called quiet zone (that is, a white border space as described here: https://delivr.com/faq/1455/whats-with-the-white-border-around-the-qr-code).

As things stand QR on that page is unscannable in both SBW and Android default scanner app, and probably in many other implementations so this is not something for SBW to fix.

**Comment by notnout** [comment]
Just for posterity: The issue is actually different - the QR code is color inverted. 

- Following wallets can read the PlebPay QR: Muun, Bitcoinbeach, CashApp
- Following wallets can't: WoS, Breez, Strike, SBW
