### ISSUE TITLE
about https://lightning-wallet.com/

### ISSUE THREAD

**Issue by ghost** [btcontract/wallet#163]
@akumaigorodski 
* https://lightning-wallet.com/ is unreachable
* is it deleted or moved permenantely?
* if it is replaced, is it **ok to replace** in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.btcontract.wallet.yml)
* replacing link in fdroid metadata will update link in fdroid client

**Comment by akumaigorodski** [comment]
It is replaced by sbw.app.

> is it ok to replace in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.btcontract.wallet.yml)

Yes, please do whatever you think is necessary here on your end.
