### ISSUE TITLE
Support Orbot(Android Tor)

### ISSUE THREAD

**Issue by ghost** [btcontract/wallet#17]
All other Android Bitcoin app don't support Tor.
So, please consider adding an option to use Orbot(SOCKS5 proxy) to connect to peers.

**Comment by btcontract** [comment]
This is a good idea, will research it.

**Comment by bad123boy** [comment]
Forgot my password

**Comment by btcontract** [comment]
@bad123boy here's what to do in your case: https://btcontract.com/#lost-password

**Comment by bad123boy** [comment]
I have did everything still.no show I have the address to prove its my money

**Comment by bad123boy** [comment]
Been trying for 5 days I just wish I would never used this wallet
somebody's gotta have my transactions

**Comment by btcontract** [comment]
@bad123boy if you do have a mnemonic code saved but it does not restore your balance after wallet recovery then there's a chance you've made a typo somewhere while you were writing it down.  

Here's a list of all the legit words a wallet can use when generating a mnemonic: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt You can try to verify that every word from your mnemonic is present in that list by using an in-page search and fix a typo if it's not.

Also, you may want to continue this discussion via email, my address is  anton.kumaigorodskiy@outlook.com

**Comment by btcontract** [comment]
Closing this as Orbot can now be used as a system wide proxy in Android, thus eliminating a need to implement this functionality in wallet.
