### ISSUE TITLE
Actually prevent screenshots of mnemonic

### ISSUE THREAD

**Issue by jandreske** [btcontract/wallet#19]
When showing the BIP39 mnemonic in the app, a warning about not taking a screenshot is shown. I assume a lot of users will ignore this, some might even be triggered to take a screenshot just because the word "screenshot" is mentioned.
Consider actually disallowing screenshots, something like

getWindow().setFlags(LayoutParams.FLAG_SECURE, LayoutParams.FLAG_SECURE);

should work on most systems I guess.

**Comment by btcontract** [comment]
Done. Didn't know this could be implemented in code, thanks for the heads up!
