### ISSUE TITLE
Segregated Witness for Simple Bitcoin Wallet?

### ISSUE THREAD

**Issue by shesek** [btcontract/wallet#20]
Are you planning to support Segregated Witness?

**Comment by btcontract** [comment]
Not sure yet. I do work on a new mobile Lightning network wallet which supports SW by design but have not yet decided whether to add SW to this one or leave it as is.

**Comment by shesek** [comment]
Alright. Just thought that you might want to know that Simple Bitcoin Wallet is [one of the last](https://www.reddit.com/r/Bitcoin/comments/5q6uk5/100_companies_services_and_projects_pledged/dcws51r/) few wallets listed on Bitcoin.org that hasn't announced planned SegWit support yet. If you do decide to support SegWit, it would be great if you could get Simple Bitcoin Wallet listed on the [segwit adoption](https://bitcoincore.org/en/segwit_adoption/) page. Cheers!

**Comment by shesek** [comment]
And BTW, I would be very interested hearing more about the mobile Lightning network you're working on. Is that work public yet?

**Comment by btcontract** [comment]
Not public just yet, I'll let you know once the repo is published. In general I closely follow the work being done here: https://github.com/ACINQ/eclair/tree/wip-bolts while making modifications to better fit it to mobile environment.

**Comment by ysangkok** [comment]
Maybe it would be useful to warn users that their wallet will stop working on August 1st?

This app is already listen on the segwit adoption page, but as "planned". Sounds like the feature is not actually planned.

**Comment by btcontract** [comment]
@ysangkok why would it stop working on August 1st?

Segwit is planned for this app, I'll update it once bitcoinj with segwit support comes out.

**Comment by ysangkok** [comment]
Sorry, that is of course not true at all. Logic error. Forgive me.

**Comment by btcontract** [comment]
@shesek well here it is: http://lightning-wallet.com/

**Comment by shesek** [comment]
@btcontract this looks great! very impressive work. thanks for the update.

a few questions:

- does it support incoming lightning payments?

- do you know whether its compatible with c-lightning? (the original eclair wallet isn't yet)

- for these of us that really like living on the edge, will you make a mainnet version too? :)

**Comment by btcontract** [comment]
Thanks,

> does it support incoming lightning payments?

Yes, it does but there is no WatchTower yet so if you receive a payment and peer breaches a contract and your node is offline for long enough time then peer will get away with that. So receiving is for testnet only for now as LN dev team hasn't started working on WatchTower specifications yet.

> do you know whether its compatible with c-lightning? (the original eclair wallet isn't yet)

If eclair mobile has problems with c-lightning then quite likely so does mine. That said, it there a known c-lightning-based node on a testnet? I'd like to give it a try.

> for these of us that really like living on the edge, will you make a mainnet version too? :)

wow this is really reckless you know, bugs keep getting found all the time. I'd prefer it to live on testnet for a week or two before considering that :)

**Comment by shesek** [comment]
> Yes, it does but there is no WatchTower yet so if you receive a payment and peer breaches a contract and your node is offline for long enough time then peer will get away with that. 

Are you planning on making this part of Olympus eventually, or will that be a separate service?

> If eclair mobile has problems with c-lightning then quite likely so does mine. That said, it there a known c-lightning-based node on a testnet? I'd like to give it a try.

Their mobile wallet doesn't support it, but I think their node does.

I have a c-lightning node you could use (which can also automatically generate invoices for you), can we IM chat somewhere?

> wow this is really reckless you know, bugs keep getting found all the time. 

haha, it definitely is! we want to start experimenting with it at the Tel Aviv Bitcoin Embassy, everyone involved know very well that its highly experimental and that any funds deposited should first be considered lost, with actually using it and making it work being a bonus ;)

**Comment by btcontract** [comment]
> Are you planning on making this part of Olympus eventually, or will that be a separate service?

WatchTower will be a part of Olympus and storage tokens will be used for storing revoked transactions.

> I have a c-lightning node you could use (which can also automatically generate invoices for you), can we IM chat somewhere?

I'm @Sooqakrisa at Telegram

Okay, if you really want mainnet I'll make a mainnet branch.
