### ISSUE TITLE
problem, transaction still pending

### ISSUE THREAD

**Issue by treakiandroid** [btcontract/wallet#23]
Hi, friend of mine did a transaction some weeks ago with your fdroid version that is still pending. So my question: when can i expect it to be done and is there a possibility to redo/reinsert it somehow??

**Comment by allennic** [comment]
+1

**Comment by btcontract** [comment]
@treakiandroid @allennic 

Typically a transaction which is pending for too long gets eventually rejected by network but wallet can't passively detect this, so you'll need to check this manually.

To check if transaction is rejected, tap it in a wallet, then tap "View on BlockExplorer" in a popup window to open an external site in a browser. If the site says transaction can't be found then it got rejected. If transaction is still there then the only option for now is to keep waiting.

In case if transaction is rejected you should rescan a blockchain in a wallet to get the funds back (app menu -> wallet setttings -> rescan blockchain).

Please note that restored wallet will appear empty at first and that is completely normal as it needs some time to catch up with network.
