### ISSUE TITLE
Crashes when creating wallet.

### ISSUE THREAD

**Issue by ghost** [btcontract/wallet#26]
CM11 KitKat 4.4.4

Log (btc):

07-12 10:29:32.954 I/Timeline(28453): Timeline: Activity_launch_request id:com.btcontract.wallet time:20473804
07-12 10:29:32.954 I/ActivityManager(2669): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.btcontract.wallet/.MainActivity} from pid 28453
07-12 10:29:33.144 I/ActivityManager(2669): Start proc com.btcontract.wallet for activity com.btcontract.wallet/.MainActivity: pid=31459 uid=10068 gids={50068, 1028, 1015, 3003, 1006}
07-12 10:29:33.194 D/ActivityThread(31459): handleBindApplication:com.btcontract.wallet
07-12 10:29:34.325 I/ActivityManager(2669): Displayed com.btcontract.wallet/.MainActivity: +1s202ms
07-12 10:29:34.325 I/Timeline(2669): Timeline: Activity_windows_visible id: ActivityRecord{41f90cb0 u0 com.btcontract.wallet/.MainActivity t67} time:20475174
07-12 10:29:35.166 I/Timeline(31459): Timeline: Activity_launch_request id:com.btcontract.wallet time:20476019
07-12 10:29:35.386 I/ActivityManager(2669): START u0 {cmp=com.btcontract.wallet/.WalletCreateActivity} from pid 31459
07-12 10:29:35.636 I/ActivityManager(2669): Displayed com.btcontract.wallet/.WalletCreateActivity: +241ms
07-12 10:29:35.966 I/Timeline(2669): Timeline: Activity_windows_visible id: ActivityRecord{41fd2590 u0 com.btcontract.wallet/.WalletCreateActivity t67} time:20476822
07-12 10:29:52.993 I/dalvikvm(31459):   at com.btcontract.wallet.WalletApp$WalletKit.encryptWallet(WalletApp.scala:100)
07-12 10:29:52.993 I/dalvikvm(31459):   at com.btcontract.wallet.WalletCreateActivity$$anon$1.startUp(WalletCreateActivity.scala:66)
07-12 10:29:53.003 E/AndroidRuntime(31459): Process: com.btcontract.wallet, PID: 31459
07-12 10:29:53.003 E/AndroidRuntime(31459): 	at com.btcontract.wallet.WalletApp$WalletKit.encryptWallet(WalletApp.scala:100)
07-12 10:29:53.003 E/AndroidRuntime(31459): 	at com.btcontract.wallet.WalletCreateActivity$$anon$1.startUp(WalletCreateActivity.scala:66)
07-12 10:29:53.003 W/ActivityManager(2669):   Force finishing activity com.btcontract.wallet/.WalletCreateActivity
07-12 10:29:55.015 I/ActivityManager(2669): Process com.btcontract.wallet (pid 31459) has died.

Log (bitcoin):

07-12 10:18:48.074 I/dalvikvm(30313):   at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:159)
07-12 10:18:48.104 E/AndroidRuntime(30313): 	at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:159)
07-12 10:19:12.128 I/dalvikvm(30350):   at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:159)
07-12 10:19:12.138 E/AndroidRuntime(30350): 	at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:159)
07-12 10:23:42.361 I/dalvikvm(30870):   at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:159)
07-12 10:23:42.361 E/AndroidRuntime(30870): 	at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:159)

**Comment by btcontract** [comment]
Thanks for reporting this. At first glance it looks like some kind of low level issue. Can you tell what's the device model and OS version?

**Comment by ikocevski** [comment]
Yes, It's a Samsung SM-G313HN running [this custom ROM](https://forum.xda-developers.com/ace-4/development/rom-cyanogenmod-11-galaxy-trend-2-t3189325).

If it's a device-specific issue just close it up I don't want to bother you, I just thought you should know it happens.

**Comment by btcontract** [comment]
Custom ROM definitely looks suspicious. I'll leave it open until I have more free time to install and test the ROM.
