### ISSUE TITLE
importing into a different wallet

### ISSUE THREAD

**Issue by hughdavenport** [btcontract/wallet#28]
What key derivation steps do you need? Trying to import one of my btcontract wallets into electrum, but when I enter in the same seed it gives no funds after an update. Same with copay. Importing into a fresh btcontract wallet works fine. So I guess that means that you use a slightly different derivation function?

**Comment by btcontract** [comment]
It uses BIP32 format while Electrum uses BIP44 by default. Compatible wallets that I know of are MultiBit for desktop (although it's developers don't recommend to use it anymore) and BreadWallet for iOS. 

Also, last Electrum release does mention in readme that it supports BIP32 now too, but you have to explicitly specify this detail when restoring a wallet.

**Comment by hughdavenport** [comment]
Hmm yeh I was ticking bip32 box on restore. Will try one of those other wallets. End goal is to get the bcash out really

**Comment by hughdavenport** [comment]
So tried out a bunch of differnt options on https://iancoleman.github.io/bip39/ but still isn't getting the public key that has my funds in it, but it imports fine into btcontract wallet. Have you had any experience exporting a wallet based on the seed alone?

**Comment by hughdavenport** [comment]
Importing into multibit hd also gives 0 balance

**Comment by hughdavenport** [comment]
Got it! In the derivation step in electrum/electron cash, put in m/0' instead of the default m/44'/0'/0. Hopefully that helps a few others get their bcash out :)

**Comment by btcontract** [comment]
That's a valuable info, thanks for digging it up! I did try my mnemonic with BreadWallet and MultiBit HD and in both cases it was a success, strange that MultiBit did not work out for you.
