### ISSUE TITLE
Buy BTC with Play Credit

### ISSUE THREAD

**Issue by blackph1ll1p** [btcontract/wallet#29]
Hi! I hope that it is not a stupid or impossible request, but I would like to ask you if is possible add an ability to buy bitcoin directly through Google Play credit. I have noticed that many app use it to unlock the "pro" version and/or for donations. And, in the case of a private, it would make it even more independent from banking circuits, in addition to make the app most versatile and complete.

**Comment by btcontract** [comment]
Well, it totally depends on Google. Right now they don't exchange their credits for bitcoins. If and once they start doing that I'll add such an option of course.

**Comment by blackph1ll1p** [comment]
Sorry for the retard. Anyway, yes it is currently impossible. For the moment I close it, if then Google will allow this feature in the future will come well.
