### ISSUE TITLE
[FEATURE] Extra the .wallet file

### ISSUE THREAD

**Issue by ghost** [btcontract/wallet#31]
I want to extract the .wallet file to import it into other Bitcoin wallet-Apps and use it with them.
Using mnemomtic-codes may work within an app but leaves me without knowledge of all my receive-addresses and I don't know if the same mnemotic code on other apps generates the same wallet.

**Comment by DrEP1980** [comment]
Amen!  I feel you on this issue.  Anyone else understand this dilemma?

**Comment by btcontract** [comment]
.wallet file is specific to applications which use bitcoinj and won't just work in any wallet, plus giving users an option whether to save a file or mnemonic brings in unnecessary complexity, I'm sure adding this feature will cause more harm than good.

Simple Bitcoin Wallet uses a BIP32-style mnemonic code with M/0' (or M/0H) generation path, it is proven to generate the same addresses in Bread Wallet for iOS and Electrum for desktop. In theory it will work on any wallet which lets you provide a BIP32 mnemonic and specify a generation path.
