### ISSUE TITLE
La billetera parece ser inválida.

### ISSUE THREAD

**Issue by Etica-Ayuda** [btcontract/wallet#32]
Hace un tiempo están intentando hacer un depósito pero no sé acredita. Hoy consulté en BlockExplorer por las transacciones de mi dirección de billetera y me informa que da error. 
¿Cuál es la solución?.

**Comment by btcontract** [comment]
If I get it right you've sent a transaction which stayed unconfirmed and now BlockExplorer can't find it.

If that's the case then you should rescan a blockchain in a wallet and the balance will be restored. Can be done via app menu -> wallet settings -> rescan blockchain

**Comment by Etica-Ayuda** [comment]
Muchas gracias por responder. No, yo no realicé la transacción. Me enviaron una suma pero no llega porque la dirección figura como inválida.

**Comment by Etica-Ayuda** [comment]
Muchas gracias por responder. No, yo no realicé la transacción. Me enviaron una suma pero no llega porque la dirección figura como inválida.

**Comment by Etica-Ayuda** [comment]
Olvidé mencionar que reescanee la cadena de bloques cuatro veces en el día.

**Comment by btcontract** [comment]
Can you please provide that 'invalid' address?

**Comment by Etica-Ayuda** [comment]
112n2gcL1XKj7WtwaarpispGXzFiQ51EcF

**Comment by btcontract** [comment]
It's a perfectly valid address as can be seen here for example: https://www.smartbit.com.au/address/112n2gcL1XKj7WtwaarpispGXzFiQ51EcF

But it is empty which only means a payee have not yet sent a funds. You probably should contact a payee and explain a situation, a link I've provided can be used as a proof of absent transaction.

**Comment by Etica-Ayuda** [comment]
He estado verificando y gracias a su enlace creo que estoy comprendiendo.
Creo me han estafado. Esperaré un tiempo más, pero todo indica que es así.
Es el precio de ser nuevo en esto. Muchas gracias por su atención y ayuda.
A su disposición.
