### ISSUE TITLE
BTC transaction pending

### ISSUE THREAD

**Issue by PubMe** [btcontract/wallet#35]
I'm getting a little nervous:
On January 4, 8 AM, I initiated a transaction of 0.15 BTC to another address.
Ever since then, the transaction has either been passively doing nothing on BlockCypher (confidence 35.86 %, never changing), every now and then it disappears from BlockCypher ("transaction not available"), when it reappears there eventually (on basis of what I have no idea), it claims to have just been received by BlockCypher - now, five days later, it claims to have been received 6 hours ago. On top of that, instead of 0.15 BTC, 0.2 was blocked, 0.15 being the requested outgoing payment, 0.000374 a fee and 0.049626 seems to be sent back. Is there any way to make the transaction to be finalized or canceled?
I tried to rescan the block chain - but it only changed the transaction information in the wallet - instead of previous payments I made to the wallet (three times 0.1 BTC deposit, 1 0.15 BTC withdrawal), it says there have been one 0.1 BTC deposit plus 0.049626 BTC deposit unconfirmed, the information about the unconfirmed transaction actually contains the original information about 0.15 BTC that should be sent to the other address.
The sums seem to be OK but the fact is that the transaction seems to be frozen, going neither back nor forth.

**Comment by btcontract** [comment]
All of this is normal, please don't worry.

Multi-day confirmation times are common these days now that demand for transactions is high and block space is limited.

BlockCypher's confidence level is their internal metric and it does not really mean much. The only thing that matters is whether a transaction is included in a block (gets a confirmation) or not. Also, Bitcoin is a decentralized network and disappearing transaction is an effect of that: one part of network may see an unconfirmed transaction while the other may not at times.

My app is an SPV wallet and as such has some shortcomings. The mess you see after rescanning may happen when unconfirmed transactions are present which is your case. It will get normalized once an unconfirmed transaction gets included in a block.

**Comment by PubMe** [comment]
Thank you very much for the prompt reply. I will just wait then.
I you don't mind, do you have any idea how long it can take? I thought it would be hours (1 day tops) but what is the reasonable time for the transaction to be processed? A week? More? Or is it completely unpredictable?

**Comment by btcontract** [comment]
Bitcoin transaction may stay unconfirmed like this for up to 5-15 days if high demand persists and in the worst scenario it may even be rejected eventually in which case you would have to rescan a blockchain in a wallet to get the funds back.

**Comment by ratati** [comment]
Tell me the same situation almost, I translated 0.0481 bitcoin exchange nickname 60sek.com, the exchange did not pass the request was cleared because of the incoming transfer, in the end not bitcoins, no transaction history of receipt and sending, how to be?
