### ISSUE TITLE
"Searching for peers"

### ISSUE THREAD

**Issue by ur-n1ghtmar3** [btcontract/wallet#40]
I am in an infinite loop of "Searching for peers". If i try to rescan blockchain nothing happens

**Comment by btcontract** [comment]
This means an app has no network access. Please check if networking works on your phone (in a browser for example). If it does then check if network access is restricted for a wallet app in phone settings.

**Comment by ur-n1ghtmar3** [comment]
Network access is ok. I solved the problem by unchecking "Connect to trusted nodes"

**Comment by btcontract** [comment]
Seems like your app version is rather outdated. Trusted nodes was an emergency measure during UASF times and was removed later.

**Comment by ur-n1ghtmar3** [comment]
Turns out my phone isn't supported now and F-Droid didn't update the app
