### ISSUE TITLE
Address Reuse

### ISSUE THREAD

**Issue by adlai** [btcontract/wallet#41]
I've noticed that the wallet sometimes gives a previously used address when using the `Receive` button on the main screen. Is this intentional or should I investigate further?

**Comment by vitamin1982** [comment]
Как сменить пароль

**Comment by btcontract** [comment]
@vitamin1982 С помощью мнемонического кода, вы его записали?

**Comment by adlai** [comment]
Это перевод моего предыдущего сообщения (я сам не говорю по-русски, поэтому я не уверен в его правильности):

Я заметил, что кошелек иногда дает ранее использованный адрес при использовании кнопки «Получить». Является ли это преднамеренным или я должен исследовать дальше?

**Comment by btcontract** [comment]
Ah yes, this is a strange behavior. Wallet should change it's current address on every incoming transaction unless funds were sent to one of old (used) addresses.
