### ISSUE TITLE
Lost BTC

### ISSUE THREAD

**Issue by mountainbcbc** [btcontract/wallet#43]
The password for the app never came up. I received BTC and i couldnt put a password in. 
i reinstalled the app and recovered the account with the 12 code and it hasnt appeared back in.
Similar instances of people having this issue!
Please respond back for further investigation.

**Comment by btcontract** [comment]
OK, most likely a mnemonic code you've provided is somehow wrong (contains a typo). This can be fixed, please check this page: https://lightning-wallet.com/recovering-lost-balance#when-your-wallet-is-restored-but-the-balance-is-zero

**Comment by btcontract** [comment]
The link is on a Lightning Wallet site but it also applies to Simple Bitcoin Wallet perfectly.

**Comment by mountainbcbc** [comment]
I'm still interested in recovering this.

**Comment by btcontract** [comment]
You can try to enter mnemonic code into updated app (v2, https://github.com/btcontract/wallet/releases/tag/2.0.2), then go to settings and add BIP32 wallet there. 

Unlike previous version now each word spelling is checked and only valid suggestions are shown, and also mnemonic phrase checksum is checked. This way you can at least rule out a possibility of invalid mnemonic.
