### ISSUE TITLE
Publish to FDROID

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#47]
In README clicking on f-droid point to https://f-droid.org/repository/browse/?fdid=com.btcontract.wallet which return 404,
thus publish the app to FDROID via opening RFP in https://gitlab.com/fdroid/rfp/

**Comment by btcontract** [comment]
An updated metadata has been merged yesterday here: https://gitlab.com/fdroid/fdroiddata/-/commit/2ede92d9bdef4ded4626672412ba96cbf679b748/pipelines?ref=master

I expect an app to become available on next site update (current timestamp on site is 2021-08-14).

**Comment by btcontract** [comment]
App is now visible at https://f-droid.org/en/packages/com.btcontract.wallet/
