### ISSUE TITLE
Add Gradle Wrapper Scripts (gradlew files)

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#48]
https://docs.gradle.org/current/userguide/gradle_wrapper.html

which will aloow building the project by running `./gradlew assembleRelease` which will use/download the gradle version specified in gradle-wrapper.properties file:
https://github.com/btcontract/wallet/blob/master/gradle/wrapper/gradle-wrapper.properties#L6

otherwise user need to install gradle manually (via package-manager or manual download) and different version will probably won't compile the app.

**Comment by btcontract** [comment]
Thanks for digging this out, I'll get to this stuff in a day or two (currently have no access to dev computer).

**Comment by btcontract** [comment]
Added wrapper files in https://github.com/btcontract/wallet/commit/59223ae0aee32c8c5ae0a76439fd531f87ad3253.
