### ISSUE TITLE
Remove JCenter lines from build.gradle or at least specify what used by it directly

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#52]
https://github.com/btcontract/wallet/blob/5d03e156522472500270e99535bf3ded45f3dbcf/build.gradle#L4
https://github.com/btcontract/wallet/blob/5d03e156522472500270e99535bf3ded45f3dbcf/build.gradle#L16

Jcenter service is closed (currently in read-only mode, no updates for packages will be made)
more details on needed migration:
https://developer.android.com/studio/build/jcenter-migration
https://blog.gradle.org/jcenter-shutdown

and here content on how to migrate:
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

You can declare specific usages of jcenter like explained in https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#consumed-dependencies-from-bintrayjcenter and like it's done for example in this PR of unstoppable wallet "Gradually migrate from jcenter to mavenCentral"
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/3752/files

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/3b240e408ad8011f60dab7f3248ade306de301b6.
