### ISSUE TITLE
Add funding.yml file & Consider adding github sponsors

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#54]
funding.yml file
https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

github sponsors
https://github.blog/2020-03-24-getting-started-with-github-sponsors/

In another project IMMORTAN under btcontract a FUNDING.yml exists in: 
https://github.com/btcontract/IMMORTAN/blob/master/.github/FUNDING.yml
which point to FUNDING.md file:
https://github.com/btcontract/immortan/blob/master/FUNDING.md

**Comment by btcontract** [comment]
Thanks, added.
