### ISSUE TITLE
Remove android.enableJetifier lines from gradle.properties

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#56]
https://github.com/btcontract/wallet/blob/5d03e156522472500270e99535bf3ded45f3dbcf/gradle.properties#L18-L19

See this guide for the steps to ensure it's safe to remove above line `android.enableJetifier=true` (check that all deps are already fully migrated to AndroidX, and migrate the ones still not migrated to it)
https://medium.com/dipien/say-bye-bye-to-android-jetifier-a7e0d388f5d6

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/c2a48d435188ee456535a7ac692e63b857798ab0.
