### ISSUE TITLE
Change APK name from "app-release" to meaningful name contains wallet name & version

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#58]
The APK file download at:
https://github.com/btcontract/wallet/releases
called `app-release.apk` it's better to name them like `SimpleBitcoinWallet-3.0.2.apk` (WalletName-Version) or something else that will be meaningful and unique to the version downloaded.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/c775cdda8c812027a8297a32a568247bfa368997.
