### ISSUE TITLE
"1st/2nd level callback domain mismatch"

### ISSUE THREAD

**Issue by HamishMacEwan** [btcontract/wallet#59]
`java.lang.IllegalArgumentException: requirement failed: 1st/2nd level callback domain mismatch`

This error arises with Lightning Address: lnbits1@merak-4.bitid.nz sending from SBW v2.0.3-63

merak-4.bitid.nz is running satdress v0.2.1, served via nginx configured with:

```
server {
    server_name merak-4.bitid.nz;
    [ssl & port configurations]
    location / {
        proxy_pass http://localhost:17422 ;
    }
```

https://lightningdecoder.com/lnbits1@merak-4.bitid.nz verifies the Lightning Address as OK.  The LNURLp metadata, from https://merak-4.bitid.nz/.well-known/lnurlp/lnbits1 is:

`{"status":"OK","callback":"https://merak-4.BitID.nz/.well-known/lnurlp/lnbits1","tag":"payRequest","maxSendable":100000000,"minSendable":1000,"metadata":"[[\"text/identifier\",\"lnbits1@merak-4.BitID.nz\"],[\"text/plain\",\"Satoshis to lnbits1@merak-4.BitID.nz.\"]]","commentAllowed":0}`

Another Lightning Address, `lnbits2@payaddress.co`, works flawlessly and seems to return similar metadata.

Can you explain what the error message means please.   Any help you can offer to address this error would be much appreciated.

**Comment by btcontract** [comment]
It looks like current SBW code does not normalize domains before comparing (so `merak-4.bitid.nz` from address and `merak-4.BitID.nz` are not the same). I guess this is overly strict and it should nomalize them before comparing.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/5c5e5dcfb77161b18da2f9178288e8e57e988e4d, provided example will work in next release.

**Comment by HamishMacEwan** [comment]
Thank you!
