### ISSUE TITLE
When I change the custom Electrum Node I have to force-restart the app for new settings to take effect

### ISSUE THREAD

**Issue by jordan-greg** [btcontract/wallet#62]
I think it would be best to reconnect immediately, or force restart the app for the user (some warning that this setting require restart and the force restart app).

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/10538c665842e732ed00c9d2e35ebc62885b7156 by offering an app restart after Electrum node has changed.
