### ISSUE TITLE
LNURL Pay issues

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#66]
Two issues, too small to open them separately.
1) The comment length limit isn't enforced in the UI, the message is truncated on sending. Test on https://chat.blixtwallet.com/ I propose showing a character counter like they did in Breez (N/M where N is the number of characters entered and M is the max number allowed)
2) To enter the comment I have to tap "Add comment" twice, first tap shows an input field, second tap lets me type there. That creates friction, one should really be enough.

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/288d8ce99d601f30f4c927e4c4b2a89f8e2e1e14.
