### ISSUE TITLE
[MPP] fail an incoming payment immediately if all HTLC slots are taken yet required sum is not reached

### ISSUE THREAD

**Issue by btcontract** [btcontract/wallet#72]

**Comment by LNBIG-COM** [comment]
Addition: all HTLC slots of channels of nodes which were in invoice for this incoming payment! ;-)

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/IMMORTAN/commit/e17b992f02f074cb807b13a738f82b7435a39b8c.

@LNBIG-COM 

unfortunately this granular channel filtering can not always be relied upon since in some cases we can receive incoming payments through private channels which were not provided in invoice:

- if we have many channels to same peer, but not all of them are included in invoice (peer may utilize non-strict forwarding and route through different local channel).
- if sender uses trampoline routing and trampoline node has direct private channels to us which were not included in invoice.

So to make sure we never fast-fail an incoming MPP which still has a chance to be fulfilled we always have to take into account all local channels, not just those provided in invoice.
