### ISSUE TITLE
deprecation warnings when compiling the app

### ISSUE THREAD

**Issue by emanuelb** [btcontract/wallet#75]
Compiling the app version 2.1.12 with steps from comment: https://github.com/btcontract/wallet/issues/63#issuecomment-924162388
result in below warnings:

```
/home/appuser/app/simplebitcoinwallet/wallet/app/src/main/java/com/btcontract/wallet/BaseActivity.scala:57: method fromHtml in object Html is deprecated: see corresponding Javadoc for more information.
    def html: Spanned = android.text.Html.fromHtml(source)
                                          ^
/home/appuser/app/simplebitcoinwallet/wallet/app/src/main/java/com/btcontract/wallet/SetupActivity.scala:98: method startActivityForResult in class ComponentActivity is deprecated: see corresponding Javadoc for more information.
  def useBackupFile(view: View): Unit = startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*"), FILE_REQUEST_CODE)
                                        ^
/home/appuser/app/simplebitcoinwallet/wallet/app/src/main/java/com/btcontract/wallet/WalletApp.scala:321: method vibrate in class Vibrator is deprecated: see corresponding Javadoc for more information.
  def vibrate: Unit = if (null != vibrator && vibrator.hasVibrator) vibrator.vibrate(Array(0L, 85, 200), -1)
                                                                             ^
/home/appuser/app/simplebitcoinwallet/wallet/app/src/main/java/com/btcontract/wallet/utils/BiometricAuth.scala:20: method canAuthenticate in class BiometricManager is deprecated: see corresponding Javadoc for more information.
  def checkAuth: Unit = biometricManager.canAuthenticate match {
                                         ^
/home/appuser/app/simplebitcoinwallet/wallet/app/src/main/java/com/btcontract/wallet/utils/BiometricAuth.scala:32: method setDeviceCredentialAllowed in class Builder is deprecated: see corresponding Javadoc for more information.
        .setDeviceCredentialAllowed(true)
         ^
/home/appuser/app/simplebitcoinwallet/wallet/app/src/main/java/com/btcontract/wallet/utils/LocalBackup.scala:39: method getExternalStoragePublicDirectory in object Environment is deprecated: see corresponding Javadoc for more information.
  def downloadsDir: File = getExternalStoragePublicDirectory(DIRECTORY_DOWNLOADS)
                           ^
there were 18 feature warnings; re-run with -feature for details
7 warnings found
```

**Comment by btcontract** [comment]
These are mostly present because wallet targets API levels down to 21 (Android 5.1) which do not have support for  modern analogues so app would crash without these lines on those phones. 

OTOH in Scala specifically there is no easy way to suppress deprecation warnings so I'd rather let these be until support for older API levels is dropped.

**Comment by emanuelb** [comment]
maybe implement solution like this? (use newer API on newer android and older api on old android versions)
https://stackoverflow.com/questions/37899856/html-fromhtml-is-deprecated-what-is-the-alternative#37899983

another solution is different APK for older API like bluewallet does? (There 2 APK file to download)
https://github.com/BlueWallet/BlueWallet/releases/tag/v6.2.7

Also show message for devices with old Android, that it's unsafe and they should upgrade the version (device firmware upgrade or replace ROM to LineageOS, etc...)

**Comment by btcontract** [comment]
> maybe implement solution like this? (use newer API on newer android and older api on old android versions)
https://stackoverflow.com/questions/37899856/html-fromhtml-is-deprecated-what-is-the-alternative#37899983

This one won't eliminate an issue as legacy line will still stay and cause warnings.

> another solution is different APK for older API like bluewallet does? (There 2 APK file to download)
https://github.com/BlueWallet/BlueWallet/releases/tag/v6.2.7

This seems too involved to maintain and I still want to have a single app in stores, guess this approach makes it impossible.

> Also show message for devices with old Android, that it's unsafe and they should upgrade the version (device firmware upgrade or replace ROM to LineageOS, etc...)

This one is reasonable even though I assume old wallet users have reasons to do what they do, I've created an issue at https://github.com/btcontract/wallet/issues/77.

**Comment by btcontract** [comment]
Added warning in https://github.com/btcontract/wallet/commit/88a2c8bb08c5b796795f078e57e682194a9b63aa for API < 24.
