### ISSUE TITLE
Invalid mac

### ISSUE THREAD

**Issue by CryptoD** [btcontract/wallet#81]
I was about to migrate from an old BLW wallet to the new SBW wallet. 

On the new SBW wallet I pick the backup file and provide 12 words phrase but keep getting the following error:

```
Backup decryption failed.
Make sure that both backup file and recovery phrase are correct.
Error details
invalid mac
```

**Comment by btcontract** [comment]
This is expected since BLW backup format is not compatible with SBW because BLW channels are themselves incompatible. 

Only chain part can be migrated through recovery phrase, channels can not.

**Comment by CryptoD** [comment]
Alright I understand. What is the best method of withdrawing or migrating funds between wallets then? The status of my _Hosted channel_ on BLW called BLW Den is _disconnected_ and _sleeping_. Can't withdraw funds.

**Comment by btcontract** [comment]
Hosted channels in BLW are discontinued, too, please send me your hosted channel state to anton.kumaigorodskiy@outlook.com or telegram @akumaigorodski and I'll refund the balance on chain.

Channel state can be exported by tapping its card in a wallet.

**Comment by CryptoD** [comment]
Problem is SOLVED. Thank you very much!
