### ISSUE TITLE
LNURL-withdraw "Waiting"

### ISSUE THREAD

**Issue by HamishMacEwan** [btcontract/wallet#83]
This LNURL-withdraw string: 

LNURL1DP68GURN8GHJ7MRWVF5HGUEWVDHK6TMHD96XSERJV9MJ7CTSDYHHVVF0D3H82UNV9APXKDN9FFU8ZJN2WYEXK62PGDP5XNNNXE2K50Z9FDX ("https://lnbits.com/withdraw/api/v1/lnurl/Bk6eJxqJjq2kiACCCNs6Uj")

Generated an invoice successfully but the transaction has remained "waiting" ⌛ for some hours.

The URL above now returns:

```
{
  "reason": "Withdraw is spent.", 
  "status": "ERROR"
}
```

There is ample incoming balance provided by a HOSTED CHANNEL and another equally sufficient that I bought from LNBIG.com (IIRC).

Orbot is running.

Paying the generated invoice myself from @lntxbot worked, but clearly I haven't benefited as much as I would from lnbits.com paying it :).

**Comment by btcontract** [comment]
> Generated an invoice successfully but the transaction has remained "waiting" hourglass for some hours.

LNURL-WITHDRAW protocol ends at wallet creating an invoice and sending it to payer or HTTP, then wallet just waits for an incoming payment to happen. If incoming payment does not happen the reason should be looked for on sender side, lnbits in this case.

**Comment by btcontract** [comment]
One other possible reason is wallet actually being offline while waiting for payment, this manifests itself by OFFLINE label and/or dimmed down channel indicators (meaning channels are offline).

**Comment by btcontract** [comment]
Coding for now since there seem to be no issue on SBW side.

**Comment by HamishMacEwan** [comment]
Thanks for the elaboration of the process.  Paying the invoice exposed by SBW and having success suggested the issue was elsewhere , I had intended to draw LNbits' attention to this.  @ArcBTC?
