### ISSUE TITLE
Can't dismiss the error message

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#87]
Steps to reproduce:
- go to https://lnurl.fiatjaf.com/
- scan lnurl-pay
- try to pay the suggested amount
- this error appears: ![Screenshot_20210926-012718](https://user-images.githubusercontent.com/184066/134787411-5ce9c573-c264-4920-9d7a-021e5e282cc6.png)
- the OK button doesn't dismiss the error, the Send/Scan/Receive buttons can't be accessed
- I have to restart the app to be able to use it

**Comment by btcontract** [comment]
Fixed in https://github.com/btcontract/wallet/commit/a6593c38a39ee6688749843c4b337bd4b9097e66.
