### ISSUE TITLE
No route found

### ISSUE THREAD

**Issue by rkfg** [btcontract/wallet#96]
First thing first, this is most probably not an SBW's fault but something wrong with my channels/nodes since it's not the only wallet that fails this particular payment route. But some other wallets succeed and I want to get to the root of it. Not an emergency but I'd appreciate your help!

The setup is like this:
my friend's node —(public channel)— my node —(private channel)— SBW. My friend has only one public channel and it's to my node (which has plenty of balanced channels). This channel behaves strangely and I don't understand why. Payments go through from Muun and lntxbot for example but fail from Electrum and SBW (both connected to my node via private channels) because they can't find a path to it. Maybe there's a path finding bug that's common between these wallets, I don't know. The channel looks absolutely normal in the public LN explorers, its only distinct feature is that its fees are zero on both sides (that's intentional!).

My question is, are there any ways to debug the path finder in SBW to see what it considers and what not (and why)? Maybe dump the whole graph to see if the channel and node are even there? Would be very helpful to see the logs and interact with the LN daemon directly via a developer console like it's done in Breez.

**Comment by btcontract** [comment]
> Would be very helpful to see the logs and interact with the LN daemon directly via a developer console like it's done in Breez.

There's no LN daemon with an API in SBW, just a native library code so this is a bit problematic.

Zero fees should not be an issue, SBW algorithms take that into account. 

One thing that SBW does is it prunes small channels from graph to make it load faster. "Small" is set to 500K SAT and anything below, if your friend's channel falls into this category then this would explain no route found.

Another thing is that SBW updates graph data once every two days so if channel is younger than that it may not be seen yet.

**Comment by btcontract** [comment]
> Is it possible to change this limit somehow or make pruning optional?

Currently the only way is to recompile an app with https://github.com/btcontract/wallet/blob/master/app/src/main/java/immortan/LNParams.scala#L219 changed.

A good way for small channels, if supported by payee node API, is to issue invoices with small channel hints embedded, this way it will work with all wallets.

**Comment by rkfg** [comment]
Thanks, we'll see what we can do!
